openapi: 3.0.0
info:
  title: Create Recurring Calendar Event API
  version: 1.0.0
  description: Create a new recurring calendar event with a recurrence pattern

paths:
  /calendar-events/recurring:
    post:
      tags:
        - Recurring Events
      summary: Create a recurring calendar event
      description: Creates a new recurring calendar event with specified recurrence pattern. The system will generate event instances based on the pattern.
      operationId: createRecurringEvent
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRecurringEventRequest'
            example:
              title: "Weekly Team Meeting"
              description: "Standup meeting with the team"
              startDate: "2024-01-15T10:00:00Z"
              endDate: "2024-01-15T11:00:00Z"
              recurrencePattern:
                type: "WEEKLY"
                interval: 1
                daysOfWeek: [1, 3, 5]
              recurrenceEndDate: "2024-12-31T23:59:59Z"
              noEndDate: false
      responses:
        '201':
          description: Recurring event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecurringEventResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    CreateRecurringEventRequest:
      type: object
      required:
        - title
        - startDate
        - endDate
        - recurrencePattern
      properties:
        title:
          type: string
          maxLength: 255
          description: Event title
          example: "Weekly Team Meeting"
        description:
          type: string
          description: Optional event description
          example: "Standup meeting with the team"
        startDate:
          type: string
          format: date-time
          description: Start date and time of the first occurrence
          example: "2024-01-15T10:00:00Z"
        endDate:
          type: string
          format: date-time
          description: End date and time of the first occurrence
          example: "2024-01-15T11:00:00Z"
        recurrencePattern:
          $ref: '#/components/schemas/RecurrencePattern'
        recurrenceEndDate:
          type: string
          format: date-time
          description: Optional end date for the recurring series
          example: "2024-12-31T23:59:59Z"
        noEndDate:
          type: boolean
          default: false
          description: If true, series has no end date (generates instances up to 2 years ahead)

    RecurrencePattern:
      type: object
      required:
        - type
        - interval
      properties:
        type:
          type: string
          enum: [DAILY, WEEKLY, MONTHLY, YEARLY]
          description: Recurrence frequency type
        interval:
          type: integer
          minimum: 1
          default: 1
          description: Recurrence interval (every N days/weeks/months/years). For MVP, must be 1.
        daysOfWeek:
          type: array
          items:
            type: integer
            minimum: 1
            maximum: 7
          description: For WEEKLY type, specifies which days of week (1=Monday, 7=Sunday)
          example: [1, 3, 5]

    RecurringEventResponse:
      type: object
      properties:
        id:
          type: integer
          description: Recurring event ID
        userId:
          type: integer
          description: User ID who owns the event
        title:
          type: string
        description:
          type: string
          nullable: true
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        recurrencePattern:
          $ref: '#/components/schemas/RecurrencePattern'
        recurrenceEndDate:
          type: string
          format: date-time
          nullable: true
        noEndDate:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

