openapi: 3.0.0
info:
  title: Delete Recurring Event Series API
  version: 1.0.0
  description: Delete a recurring event series with options for past and future instances

paths:
  /calendar-events/recurring/{recurringEventId}:
    delete:
      tags:
        - Recurring Events
      summary: Delete recurring event series
      description: Deletes a recurring event series. Options allow deleting all instances, only future instances, or only past instances.
      operationId: deleteRecurringEventSeries
      security:
        - bearerAuth: []
      parameters:
        - name: recurringEventId
          in: path
          required: true
          schema:
            type: integer
          description: ID of the recurring event series
        - name: deleteOption
          in: query
          required: false
          schema:
            type: string
            enum: [all, future, past]
            default: all
          description: |
            - 'all': Delete all instances (past and future)
            - 'future': Delete only future instances (past instances remain)
            - 'past': Delete only past instances (future instances remain)
      responses:
        '200':
          description: Recurring event series deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  deletedInstances:
                    type: integer
                    description: Number of instances deleted
        '404':
          description: Recurring event not found
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user does not own this event
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

