import {
  Entity,
  Column,
  UpdateDateColumn,
  PrimaryGeneratedColumn,
  CreateDateColumn,
} from 'typeorm';

/**
 * NoteAudio entity stores metadata for TTS audio files generated by Hermes.
 * One note can have multiple audio files (history).
 * Files are stored in Hermes, metadata is stored in Chronus.
 */
@Entity('note_audios')
export class NoteAudio {
  @PrimaryGeneratedColumn({ type: 'integer' })
  id: number;

  @Column({ name: 'note_id', type: 'integer' })
  noteId: number;

  @Column({ name: 'file_path', type: 'text' })
  filePath: string;

  @Column({ name: 'file_name', type: 'text' })
  fileName: string;

  @Column({ name: 'file_format', type: 'varchar', length: 10 })
  fileFormat: string;

  @CreateDateColumn({ name: 'created_at', type: 'text' })
  createdAt: string;

  @UpdateDateColumn({ name: 'updated_at', type: 'text' })
  updatedAt: string;
}
