openapi: 3.0.0
info:
  title: Create Calendar Event API
  version: 1.0.0
  description: Endpoint to create a new calendar event

paths:
  /calendar-events:
    post:
      summary: Create a new calendar event
      operationId: createCalendarEvent
      tags:
        - Calendar Events
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCalendarEventRequest'
            example:
              title: "Team Meeting"
              description: "Weekly team sync"
              startDate: "2024-12-30T10:00:00Z"
              endDate: "2024-12-30T11:00:00Z"
      responses:
        '201':
          description: Calendar event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarEventResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateCalendarEventRequest:
      type: object
      required:
        - title
        - startDate
        - endDate
      properties:
        title:
          type: string
          maxLength: 255
          description: Event title
          example: "Team Meeting"
        description:
          type: string
          nullable: true
          description: Optional event description
          example: "Weekly team sync"
        startDate:
          type: string
          format: date-time
          description: Event start date and time (ISO 8601)
          example: "2024-12-30T10:00:00Z"
        endDate:
          type: string
          format: date-time
          description: Event end date and time (ISO 8601)
          example: "2024-12-30T11:00:00Z"

    CalendarEventResponse:
      type: object
      properties:
        id:
          type: integer
          description: Event unique identifier
          example: 1
        userId:
          type: integer
          description: User who owns the event
          example: 123
        title:
          type: string
          description: Event title
          example: "Team Meeting"
        description:
          type: string
          nullable: true
          description: Event description
          example: "Weekly team sync"
        startDate:
          type: string
          format: date-time
          description: Event start date and time
          example: "2024-12-30T10:00:00Z"
        endDate:
          type: string
          format: date-time
          description: Event end date and time
          example: "2024-12-30T11:00:00Z"
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2024-12-30T09:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2024-12-30T09:00:00Z"

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 400
        message:
          type: string
          example: "Validation failed"
        error:
          type: string
          example: "Bad Request"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

