openapi: 3.0.0
info:
  title: Fetch Calendar Event API
  version: 1.0.0
  description: Endpoint to fetch a specific calendar event by ID

paths:
  /calendar-events/{id}:
    get:
      summary: Fetch a specific calendar event
      operationId: fetchCalendarEvent
      tags:
        - Calendar Events
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Calendar event ID
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Calendar event details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarEventResponse'
        '404':
          description: Event not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - user does not own this event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CalendarEventResponse:
      type: object
      properties:
        id:
          type: integer
          description: Event unique identifier
          example: 1
        userId:
          type: integer
          description: User who owns the event
          example: 123
        title:
          type: string
          description: Event title
          example: "Team Meeting"
        description:
          type: string
          nullable: true
          description: Event description
          example: "Weekly team sync"
        startDate:
          type: string
          format: date-time
          description: Event start date and time
          example: "2024-12-30T10:00:00Z"
        endDate:
          type: string
          format: date-time
          description: Event end date and time
          example: "2024-12-30T11:00:00Z"
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2024-12-30T09:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2024-12-30T09:00:00Z"

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 404
        message:
          type: string
          example: "Calendar event not found"
        error:
          type: string
          example: "Not Found"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

